# Generated by Django 3.1.1 on 2020-11-21 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201121_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replies',
            name='replies',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='reply_id',
        ),
        migrations.AddField(
            model_name='replies',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='auctions.comment'),
        ),
        migrations.AddField(
            model_name='replies',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='replies',
            name='reply',
            field=models.ManyToManyField(blank=True, related_name='reply', to='auctions.Comment'),
        ),
    ]
