# Generated by Django 3.1.1 on 2020-11-22 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201121_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replies',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='reply',
        ),
        migrations.AddField(
            model_name='replies',
            name='commenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replies',
            name='content',
            field=models.TextField(default='', verbose_name='Replies'),
        ),
        migrations.AddField(
            model_name='replies',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='replies',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='auctions.comment'),
        ),
    ]
