# Generated by Django 3.1.1 on 2020-11-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201122_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='content',
            field=models.TextField(default='', null=True, verbose_name='Replies'),
        ),
    ]
